version: '3.7'
services:
   postgres:
      image: postgres:latest
      environment:
        POSTGRES_DB: "app_db"
        POSTGRES_USER: "user"
        POSTGRES_PASSWORD: "password"
      volumes:
        - ./data:/var/lib/postgres
      ports:
        - "5432:5432"